moroshko/basis

website/package-lock.json
website/package.json

Revert "Update dependency @react-hook/mouse-position to v4"

---

src/components/Frequency.js
src/components/Input.js
src/components/Input.test.js
src/components/internal/InternalInput.js
src/themes/default/input.js
website/src/pages/components/input/index.js
website/src/pages/kitchen-sink/components/input.js

* Renamed `numericPrefix` to `prefix`.
* Renamed `numericSuffix` to `suffix`.
* `prefix` and `suffix` can be used now with `variant="decimal"`.

Input changes

---

src/components/Input.test.js
src/components/internal/InternalInput.js

Add email type to Input component

Add email type to Input component

---

src/components/Input/types.ts

Fix the missing `validateData` prop in `<Input />`

Fix missing validateData prop in Input

---

src/components/RadioGroup/types.ts

Fix RadioGroup typescript error for array as const

---

package.json
src/components/Form/Form.test.tsx
src/components/Select/Select.tsx
src/components/Select/Select_deprecated.test.js
src/components/Select/Select_deprecated.tsx
src/components/Select/index.tsx
src/components/Select/types.ts
src/components/componentNames.ts
src/components/internal/InternalSelect.tsx
src/hooks/useBasisForm/nameToDefaultValueMap.ts
src/hooks/useBasisForm/nameToValidateMap.ts
src/hooks/useBasisForm/validation/validateSelect.ts
src/utils/test.js
website/src/pages/components/form2/index.js
yarn.lock

Updated the Select and Form and added the pre-commit hook.

Updated Select to new Form pattern and pre-commit

---

src/hooks/useBasisForm/nameToValidateMap.ts
src/hooks/useBasisForm/validation/index.ts
src/index.ts

Exported the default validation functions from within basis

Expose the default validation functions from basis

---

src/components/Field/Field.tsx
src/hooks/useBasisForm/useBasisField.ts
src/types.ts

Fixed the default value tyepscript error for field array

Fix default value typescript error for field array

---

MIGRATING_TO_NEW_FORM.md

Added migration doc for the new form pattern

Add migration to new form doc

---

src/components/Textarea/Textarea.test.js
src/components/Textarea/Textarea.tsx
src/components/Textarea/Textarea_deprecated.js
src/components/Textarea/defaultTextareaProps.ts
src/components/Textarea/index.tsx
src/components/Textarea/types.ts
src/components/componentNames.ts
src/hooks/useBasisForm/nameToDefaultValueMap.ts
src/hooks/useBasisForm/nameToValidateMap.ts
src/hooks/useBasisForm/validation/index.ts
src/hooks/useBasisForm/validation/validateTextarea.ts

Updated Textarea to new pattern

Update Textarea to new form pattern

---

src/components/Textarea/types.ts

Add missing height prop in Textarea

---

src/components/DateInput/DateInput.tsx
src/components/DateInput/types.ts
src/components/Form/Form.test.tsx
src/components/Frequency/Frequency.tsx
src/components/Frequency/Frequency__deprecated.js
src/components/Frequency/Frequency__deprecated.test.js
src/components/Frequency/defaultFrequencyProps.ts
src/components/Frequency/index.tsx
src/components/Frequency/types.ts
src/components/componentNames.ts
src/components/internal/InternalRadioGroup.tsx
src/components/internal/InternalSelect.tsx
src/hooks/useBasisForm/nameToDefaultValueMap.ts
src/hooks/useBasisForm/nameToValidateMap.ts
src/hooks/useBasisForm/validation/index.ts
src/hooks/useBasisForm/validation/validateDateInput.ts
src/hooks/useBasisForm/validation/validateFrequency.ts
src/hooks/useBasisForm/validation/validateInput.ts
src/hooks/useBasisForm/validation/validateRadioGroup.ts
src/hooks/useBasisForm/validation/validateSelect.ts
src/hooks/useBasisForm/validation/validateTextarea.ts
src/index.ts
src/types.ts
src/utils/test.js
src/values.ts

Updated frequency to the new form pattern

Update frequency to new form pattern

---

src/components/Stack.tsx

Fix Stack margin type

---

src/components/Field/CustomField.tsx
src/components/Field/types.ts
src/components/Form/Form.test.tsx
src/hooks/useBasisForm/useBasisField.ts
src/hooks/useBasisForm/useBasisForm.ts

Add custom field component

---

package.json
src/components/Checkbox/Checkbox.tsx
src/components/internal/InternalCheckbox.tsx
src/hooks/useBasisForm/useBasisField.ts
yarn.lock

Fix complex input's being rendered as object object
see: https://github.com/react-hook-form/react-hook-form/discussions/5548#discussioncomment-849081

Fix some inputs being rendered as [object Object]

---

src/components/Input/Input.tsx
src/components/Input/types.ts
src/components/internal/InternalInput.tsx

Enable Key down event property on Input component.

Input keydown 

---

src/components/RadioGroup/RadioGroup.tsx
src/components/RadioGroup/types.ts
src/index.ts

Adding name to radio group if one is not provided, forwarding name if it is provided
Also exporting Color and some types to allow easier integration with Theme

Fix for radio group tabbing

---

src/components/DatePicker.js
src/components/internal/InternalInput.js

Improve accessibility for `DatePicker`

Added aria-labels to DatePicker

---

src/components/Form/Form.tsx
src/components/Grid.tsx
src/components/Stack.tsx
src/components/Text.tsx
src/components/Textarea/Textarea.tsx
src/components/internal/Field.tsx
src/components/internal/InternalCheckbox.tsx
src/components/internal/InternalInput.tsx
src/components/internal/InternalRadioGroup.tsx
src/components/internal/InternalSelect.tsx
src/hooks/useBackground.tsx
src/hooks/useResponsivePropsCSS.ts
src/hooks/useTextStyle.ts
src/themes/default/autoComplete.ts
src/themes/types.ts
src/types.ts
src/utils/css.ts
src/utils/theme.ts

Convert `useResponsivePropsCss` to typescript allowing removal of `@ts-ignore` comments.
Also added proper proptypes to `Text`

Convert useResponsivePropsCss to TS

---

package.json
rollup.config.js
src/index.ts
tsconfig.json
yarn.lock

Fixed typescript errors

---

src/hooks/useBasisForm/nameToDefaultValueMap.ts
src/hooks/useBasisForm/useBasisField.ts
src/hooks/useWrapperFocus.ts

Fixed the following:
- validation for autocomplete
- triggering the validation for autcomplete inside an iframe

Fixed Autocomplete validation

---

src/components/Field/types.ts
src/components/Form/Form.test.tsx
src/hooks/useBasisForm/useBasisField.ts
src/hooks/useBasisForm/useBasisForm.ts
src/hooks/useBasisForm/useBasisFormContext.ts
src/index.ts
src/types.ts

Changes:
- Fixed set basis error
- exported types to allow consumers to create `composeValidation` function.

Fixed set basis error
